# Generated by Django 4.2.16 on 2024-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='housing',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
