# Generated by Django 4.2.16 on 2024-10-19 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_housing_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housing',
            name='photo_1',
        ),
        migrations.CreateModel(
            name='HousingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('housing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.housing')),
            ],
        ),
    ]
