# Generated by Django 4.2.16 on 2024-11-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='water_bill',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
