# Generated by Django 4.2.16 on 2024-11-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_tenant_water_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.PositiveIntegerField(unique=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.housing')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tenant')),
            ],
        ),
    ]
